version: '3.6'
services: 
    alpine-postgres:
        image: onjin/alpine-postgres
        restart: always
        environment: 
            - DATABASE_HOST=127.0.0.1
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=booking_db
        ports: 
            - "8001:5432"
        volumes: 
            - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql