 CREATE TABLE Event (EVENTID VARCHAR(255) NOT NULL, NUMBEROFTICKETS INTEGER, PRIMARY KEY (EVENTID));
 CREATE TABLE OrderTable (ID INTEGER NOT NULL, DELIVERYMETHOD VARCHAR(255), ORDEREDAT TIMESTAMP, PAYMENTMETHOD VARCHAR(255), TICKETQUANTITY INTEGER, USERNAME VARCHAR(255), EVENT_EVENTID VARCHAR(255), PRIMARY KEY (ID));
